spring:
datasource:
url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/scm
username: ${DB_USER:scm}
password: ${DB_PASS:scm}
jpa:
hibernate:
ddl-auto: validate
properties:
hibernate:
format_sql: true
kafka:
bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
producer:
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
consumer:
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


app:
default-warehouse: WH-1


logging:
level:
root: INFO
com.scm: DEBUG
